const jobRoles = [
	"Software Developer",
	"Systems Administrator",
	"Network Engineer",
	"Cybersecurity Analyst",
	"Data Scientist",
	"Database Administrator",
	"Web Developer",
	"IT Project Manager",
	"DevOps Engineer",
	"Cloud Architect",
	"Technical Support Engineer",
	"Business Analyst",
	"IT Consultant",
	"UI/UX Designer",
	"Quality Assurance Engineer",
	"Artificial Intelligence Engineer",
	"Machine Learning Engineer",
	"IT Manager",
	"Full Stack Developer",
	"Mobile App Developer",
	"Systems Analyst",
	"Network Administrator",
	"Computer Systems Analyst",
	"Software Engineer",
	"Data Analyst",
	"IT Auditor",
	"IT Security Specialist",
	"Solution Architect",
	"IT Trainer",
	"ERP Consultant",
	"IT Sales Professional",
	"IT Procurement Specialist",
	"IT Compliance Officer",
	"IT Risk Analyst",
	"Blockchain Developer",
	"IT Business Analyst",
	"Network Security Engineer",
	"Penetration Tester",
	"Systems Integrator",
	"IT Support Specialist",
	"Cloud Engineer",
	"Data Engineer",
	"IT Recruiter",
	"IT Operations Manager",
	"IT Service Delivery Manager",
	"Virtualization Engineer",
	"Systems Engineer",
	"Embedded Systems Engineer",
	"Data Architect",
	"IT Asset Manager",
	"ITIL Service Manager",
	"Information Security Manager",
	"IT Forensic Investigator",
	"IT Change Manager",
	"IT Help Desk Technician",
	"Wireless Network Engineer",
	"IT Governance Analyst",
	"Business Intelligence Analyst",
	"Front End Developer",
	"Back End Developer",
	"Software Tester",
	"Mobile Application Tester",
	"IT Business Continuity Manager",
	"Data Warehouse Developer",
	"IT Capacity Planner",
	"IT Systems Analyst",
	"IT Performance Analyst",
	"IT Contracts Manager",
	"IT Vendor Manager",
	"Network Operations Center (NOC) Technician",
	"IT Service Desk Manager",
	"Data Center Manager",
	"IT Facilities Manager",
	"IT Disaster Recovery Specialist",
	"IT Compliance Auditor",
	"IT Systems Administrator",
	"IT Security Auditor",
	"IT Financial Analyst",
	"IT Service Continuity Manager",
	"IT Problem Manager",
	"IT Release Manager",
	"IT Deployment Manager",
	"IT Configuration Manager",
	"IT Incident Manager",
	"IT Service Catalog Manager",
	"IT Service Level Manager",
	"IT Service Portfolio Manager",
	"IT Knowledge Manager",
	"IT Training Manager",
	"IT Communications Manager",
	"IT Reporting Analyst",
	"IT Metrics Analyst",
	"IT Process Analyst",
	"IT Cost Analyst",
	"IT Procurement Analyst",
	"IT Service Desk Analyst",
	"IT Field Support Analyst",
	"IT Asset Analyst",
	"IT Help Desk Analyst",
	"IT Desktop Support Analyst"
];

export default jobRoles;
