export const degrees = [
	"Associate of Applied Science",
	"Associate of Arts",
	"Associate of Science",

	"Bachelor of Applied Science (BASc)",
	"Bachelor of Arts (B.A)",
	"Bachelor of Business Administration (BBA)",
	"Bachelor of Computing (B.Comp)",
	"Bachelor of Computer Applications (BCA)",
	"Bachelor of Engineering (B.E)",
	"Bachelor of Informatics",
	"Bachelor of Information Systems (BIS)",
	"Bachelor of Information Technology (BIT)",
	"Bachelor of Science (B.Sc)",
	"Bachelor of Science in Engineering (BSE)",
	"Bachelor of Technology (B.Tech)",
	"Bachelor of Technology Education (B.Tech.Ed)",

	"Diploma",

	"Doctor of Engineering (Eng.D)",
	"Doctor of Information Technology (DIT)",
	"Doctor of Philosophy (Ph.D)",
	"Doctor of Professional Studies (DPS)",
	"Doctor of Technical Sciences (Dr. Tech)",

	"Master of Arts (M.A)",
	"Master of Computer Applications (MCA)",
	"Master of Computer Science (MCS)",
	"Master of Engineering (M.E)",
	"Master of Engineering Management (MEM)",
	"Master of Information Systems (MIS)",
	"Master of Information Technology (MIT)",
	"Master of Professional Studies (MPS)",
	"Master of Science (M.Sc)",
	"Master of Science in Engineering (MSE)",
	"Master of Technology (M.Tech)"
];


export const fieldsOfStudy = [
	"Artificial Intelligence and Machine Learning",
	"Cloud Computing",
	"Computer Engineering",
	"Computer Forensics",
	"Computer Science",
	"Cybersecurity",
	"Data Science",
	"Data Science and Analytics",
	"E-Commerce and Digital Business",
	"Electrical & Electronics Engineering",
	"Electrical & Communication Engineering",
	"Game Development",
	"Health Informatics",
	"Human-Computer Interaction",
	"Information Systems",
	"Information Technology",
	"Networking and Telecommunications",
	"Robotics",
	"Software Engineering",
	"Web Development and Design"
];


export const universities = [
	"Vellore Institute of Technology (VIT)",
	"Birla Institute of Technology and Science (BITS)",
	"SRM Institute of Science and Technology",
	"Amrita Vishwa Vidyapeetham",
	"Amity University",
	"Thapar Institute of Engineering and Technology",
	"Chandigarh University",
	"Manipal Institute of Technology",
	"International Institute of Information Technology (IIIT)",
	"Lovely Professional University (LPU)",
	"Graphic Era University",
	"Sathyabama Institute of Science and Technology",
	"Saveetha Institute of Medical and Technical Sciences",
	"Dr. Vishwanath Karad MIT World Peace University",
	"Galgotias University",
	"Hindustan Institute of Technology and Science (HITS)",
	"Kalinga Institute of Industrial Technology (KIIT)",
	"Banasthali Vidyapith",
	"Jaypee Institute of Information Technology",
	"Shiv Nadar University",
	"Ashoka University",
	"UPES (University of Petroleum and Energy Studies)",
	"MIT World Peace University",
	"Christ University",
	"SRM University",
	"REVA University",
	"Sharda University",
	"Dhirubhai Ambani Institute of Information and Communication Technology (DAIICT)",
	"Kumaraguru College of Technology",
	"Sri Sivasubramaniya Nadar (SSN) College of Engineering"
];


export const schools = [
	"The Doon School",
	"The Shri Ram School",
	"Dhirubhai Ambani International School",
	"Cathedral and John Connon School",
	"La Martiniere for Boys",
	"La Martiniere for Girls",
	"Modern School, Barakhamba Road",
	"The Mother's International School",
	"Welham Boys' School",
	"Welham Girls' School",
	"St. Xavier's Collegiate School",
	"The Scindia School",
	"Mayo College",
	"Mayo College Girls' School",
	"Sanskriti School",
	"Pathways World School",
	"Woodstock School",
	"International School Bangalore (TISB)",
	"Indus International School",
	"Sardar Patel Vidyalaya",
	"Jamnabai Narsee School",
	"Inventure Academy",
	"Oakridge International School",
	"Sishya School",
	"National Public School (NPS)",
	"Delhi Public School (DPS)",
	"Hebron School"
];


export const boardNames = [
	"The Jammu & Kashmir State Board of School Education",
	"Jammu and Kashmir State Open School",
	"Himachal Pradesh Board of School Education",
	"Punjab School Education Board",
	"Board of School Education, Uttarakhand",
	"Uttarakhand Sanskrit Shiksha Parishad",
	"Uttarakhand Madrasa Education Board",
	"Bhartiya Shiksha Board, Uttarakhand",
	"Gurukula Kangri Vishwavidyalaya, Uttarakhand",
	"Board of School Education, Haryana",
	"Central Board of Secondary Education (CBSE)",
	"Council for the Indian School Certificate Examinations (CISCE)",
	"Indian School Certificate (ISC)",
	"Indian Council of Secondary Education / Indian School Certificate Examinations (ICSE)",
	"National Institute of Rural Open Schooling, New Delhi",
	"Delhi Board of Senior Secondary Education",
	"Delhi State Open School",
	"Uttar Pradesh Board of High School & Intermediate Education",
	"Uttar Pradesh Board of SEC. Sanskrit Education",
	"National Institute of Open Schooling (NIOS)",
	"Dayalbagh Educational Institute, Uttar Pradesh",
	"Board of Secondary Education, Rajasthan",
	"Rajasthan State Open School",
	"Banasthali Vidyapith, Rajasthan",
	"Bihar School Examination Board",
	"Bihar Board of Open Schooling & Examination",
	"Bihar State Madrasa Education Board",
	"Bihar Sanskrit Shiksha Board",
	"West Bengal Board of Secondary Education",
	"West Bengal Council of Higher Secondary Education",
	"West Bengal Board of Madrassa Education",
	"The West Bengal Council of Rabindra Open Schooling",
	"West Bengal State Council of Technical & Vocational Education",
	"Board of Open Schooling and Skill Education, Sikkim",
	"Assam Higher Secondary Education Council",
	"Board of Secondary Education, Assam",
	"Assam Sanskrit Board",
	"State Madrassa Education Board, Assam",
	"Meghalaya Board of School Education",
	"Nagaland Board of School Education",
	"Board of Secondary Education, Manipur",
	"Council of Higher Secondary Education, Manipur",
	"Mizoram Board of School Education",
	"Tripura Board of Secondary Education",
	"Jharkhand Academic Council, Ranchi",
	"Board of Secondary Education, Madhya Pradesh",
	"M.P. State Open School Education Board",
	"Maharishi Patanjali Sanskrit Sansthan",
	"Gujarat Secondary and Higher Secondary Education Board",
	"Maharashtra State Board of Secondary and Higher Secondary Education",
	"Council of Universal Buddhist University, Nagpur",
	"Chhattisgarh Board of Secondary Education",
	"Chhattisgarh State Open School",
	"Chhattisgarh Sanskrit Board, Raipur",
	"Chhattisgarh Madrasa Board",
	"Council of Higher Secondary Education, Odisha",
	"Board of Secondary Education, Odisha",
	"Odisha State Board of Madrassa Education",
	"Telangana State Board of Intermediate Education",
	"Board of Secondary Education, Telangana State",
	"Telangana Open School Society",
	"Rajiv Gandhi Institute of Knowledge Technologies",
	"Board of Intermediate Education (Andhra Pradesh)",
	"Board of Secondary Education (Andhra Pradesh)",
	"A.P. Open School Society Govt. of Andhra Pradesh",
	"Goa Board of Secondary and Higher Secondary Education",
	"Govt. of Karnataka Dept. of Pre-University Education",
	"Karnataka Secondary Education, Examination Board",
	"State Board of School Examinations (Sec.) & Board of Higher Secondary Examinations, Tamil Nadu",
	"Kerala Board of Public Examination",
	"Kerala Board of Higher Secondary Education",
	"Board of Vocational Higher Secondary Education, Kerala"
];
