const targetCountries = [
  { name: "Australia", code: "+61", currency: "AUD", symbol: "A$", currencyName: "Australian Dollar" },
  { name: "Austria", code: "+43", currency: "EUR", symbol: "€", currencyName: "Euro" },
  { name: "Belgium", code: "+32", currency: "EUR", symbol: "€", currencyName: "Euro" },
  { name: "Brazil", code: "+55", currency: "BRL", symbol: "R$", currencyName: "Brazilian Real" },
  { name: "Canada", code: "+1", currency: "CAD", symbol: "C$", currencyName: "Canadian Dollar" },
  { name: "China", code: "+86", currency: "CNY", symbol: "¥", currencyName: "Chinese Yuan" },
  { name: "Czech Republic", code: "+420", currency: "CZK", symbol: "Kč", currencyName: "Czech Koruna" },
  { name: "Denmark", code: "+45", currency: "DKK", symbol: "kr", currencyName: "Danish Krone" },
  { name: "Finland", code: "+358", currency: "EUR", symbol: "€", currencyName: "Euro" },
  { name: "France", code: "+33", currency: "EUR", symbol: "€", currencyName: "Euro" },
  { name: "Germany", code: "+49", currency: "EUR", symbol: "€", currencyName: "Euro" },
  { name: "Iceland", code: "+354", currency: "ISK", symbol: "kr", currencyName: "Icelandic Króna" },
  { name: "India", code: "+91", currency: "INR", symbol: "₹", currencyName: "Indian Rupee" },
  { name: "Indonesia", code: "+62", currency: "IDR", symbol: "Rp", currencyName: "Indonesian Rupiah" },
  { name: "Ireland", code: "+353", currency: "EUR", symbol: "€", currencyName: "Euro" },
  { name: "Israel", code: "+972", currency: "ILS", symbol: "₪", currencyName: "Israeli New Shekel" },
  { name: "Italy", code: "+39", currency: "EUR", symbol: "€", currencyName: "Euro" },
  { name: "Japan", code: "+81", currency: "JPY", symbol: "¥", currencyName: "Japanese Yen" },
  { name: "South Korea", code: "+82", currency: "KRW", symbol: "₩", currencyName: "South Korean Won" },
  { name: "Malaysia", code: "+60", currency: "MYR", symbol: "RM", currencyName: "Malaysian Ringgit" },
  { name: "Mexico", code: "+52", currency: "MXN", symbol: "$", currencyName: "Mexican Peso" },
  { name: "Netherlands", code: "+31", currency: "EUR", symbol: "€", currencyName: "Euro" },
  { name: "New Zealand", code: "+64", currency: "NZD", symbol: "NZ$", currencyName: "New Zealand Dollar" },
  { name: "Nigeria", code: "+234", currency: "NGN", symbol: "₦", currencyName: "Nigerian Naira" },
  { name: "Norway", code: "+47", currency: "NOK", symbol: "kr", currencyName: "Norwegian Krone" },
  { name: "Philippines", code: "+63", currency: "PHP", symbol: "₱", currencyName: "Philippine Peso" },
  { name: "Poland", code: "+48", currency: "PLN", symbol: "zł", currencyName: "Polish Złoty" },
  { name: "Russia", code: "+7", currency: "RUB", symbol: "₽", currencyName: "Russian Ruble" },
  { name: "Saudi Arabia", code: "+966", currency: "SAR", symbol: "﷼", currencyName: "Saudi Riyal" },
  { name: "Singapore", code: "+65", currency: "SGD", symbol: "S$", currencyName: "Singapore Dollar" },
  { name: "South Africa", code: "+27", currency: "ZAR", symbol: "R", currencyName: "South African Rand" },
  { name: "Spain", code: "+34", currency: "EUR", symbol: "€", currencyName: "Euro" },
  { name: "Sweden", code: "+46", currency: "SEK", symbol: "kr", currencyName: "Swedish Krona" },
  { name: "Switzerland", code: "+41", currency: "CHF", symbol: "CHF", currencyName: "Swiss Franc" },
  { name: "Taiwan", code: "+886", currency: "TWD", symbol: "NT$", currencyName: "New Taiwan Dollar" },
  { name: "Ukraine", code: "+380", currency: "UAH", symbol: "₴", currencyName: "Ukrainian Hryvnia" },
  { name: "United Arab Emirates", code: "+971", currency: "AED", symbol: "د.إ", currencyName: "UAE Dirham" },
  { name: "United Kingdom", code: "+44", currency: "GBP", symbol: "£", currencyName: "British Pound Sterling" },
  { name: "United States", code: "+1", currency: "USD", symbol: "$", currencyName: "US Dollar" }
];
export default targetCountries;
