const coursesList = {
    'Basics': [
        {
            'title': 'Full Stack AI',
            'route': '/(protected)/home/courses/courses/1',
            'available': true,
            'time': '20 Hours',
        },
        {
            'title': 'Generative AI Fundamentals',
            'route': '/(freeRoutes)/home/courseUnavailable/Generative AI Fundamentals',
            'available': false,
            'time': '0 Hours'
        },
        {
            'title': "Prompt Engineering Mastery",
            'route': '/(freeRoutes)/home/courseUnavailable/Prompt Engineering Mastery',
            'available': false,
            'time': '0 Hours'
        },
        {
            'title': "Data Engineering for AI",
            'route': '/(freeRoutes)/home/courseUnavailable/Data Engineering for AI',
            'available': false,
            'time': '0 Hours'
        },
        {
            'title': "AI Project Architecture & MLOps",
            'route': '/(freeRoutes)/home/courseUnavailable/AI Project Architecture & MLOps',
            'available': false,
            'time': '0 Hours'
        },
        {
            'title': "Responsible AI & Safety",
            'route': '/(freeRoutes)/home/courseUnavailable/Responsible AI & Safety',
            'available': false,
            'time': '0 Hours'
        }
    ],
    'Text': [
        { title: 'Spam Detection (Text Classification)', route: '/(freeRoutes)/home/courseUnavailable/Spam Detection (Text Classification)', available: false, time: '0 Hours' },
        { title: 'Sentiment Analysis', route: '/(freeRoutes)/home/courseUnavailable/Sentiment Analysis', available: false, time: '0 Hours' },
        { title: 'Language Detection', route: '/(freeRoutes)/home/courseUnavailable/Language Detection', available: false, time: '0 Hours' },
        { title: 'Keyword Extraction', route: '/(freeRoutes)/home/courseUnavailable/Keyword Extraction', available: false, time: '0 Hours' },
        { title: 'Bag-of-Words vs TF-IDF Comparison', route: '/(freeRoutes)/home/courseUnavailable/Bag-of-Words vs TF-IDF Comparison', available: false, time: '0 Hours' },
        { title: 'Word Cloud Visualization', route: '/(freeRoutes)/home/courseUnavailable/Word Cloud Visualization', available: false, time: '0 Hours' },
        { title: 'Fake News Detection (Basic)', route: '/(freeRoutes)/home/courseUnavailable/Fake News Detection (Basic)', available: false, time: '0 Hours' },
        { title: 'Named Entity Recognition (NER)', route: '/(freeRoutes)/home/courseUnavailable/Named Entity Recognition (NER)', available: false, time: '0 Hours' },
        { title: 'POS Tagging', route: '/(freeRoutes)/home/courseUnavailable/POS Tagging', available: false, time: '0 Hours' },
        { title: 'Text Summarization (Extractive)', route: '/(freeRoutes)/home/courseUnavailable/Text Summarization (Extractive)', available: false, time: '0 Hours' },
        { title: 'Topic Modeling', route: '/(freeRoutes)/home/courseUnavailable/Topic Modeling', available: false, time: '0 Hours' },
        { title: 'Document Similarity / Semantic Search', route: '/(freeRoutes)/home/courseUnavailable/Document Similarity / Semantic Search', available: false, time: '0 Hours' },
        { title: 'Question Answering (Basic)', route: '/(freeRoutes)/home/courseUnavailable/Question Answering (Basic)', available: false, time: '0 Hours' },
        { title: 'Text Clustering', route: '/(freeRoutes)/home/courseUnavailable/Text Clustering', available: false, time: '0 Hours' },
        { title: 'Text Generation with RNN/LSTM', route: '/(freeRoutes)/home/courseUnavailable/Text Generation with RNN/LSTM', available: false, time: '0 Hours' },
        { title: 'Machine Translation (Seq2Seq)', route: '/(freeRoutes)/home/courseUnavailable/Machine Translation (Seq2Seq)', available: false, time: '0 Hours' },
        { title: 'Chatbot Development (Rule + Neural)', route: '/(freeRoutes)/home/courseUnavailable/Chatbot Development (Rule + Neural)', available: false, time: '0 Hours' },
        { title: 'Grammar Autocorrector', route: '/(freeRoutes)/home/courseUnavailable/Grammar Autocorrector', available: false, time: '0 Hours' },
        { title: 'Poetry / Story Generation', route: '/(freeRoutes)/home/courseUnavailable/Poetry / Story Generation', available: false, time: '0 Hours' },
        { title: 'Advanced Sentiment Analysis with Transformers', route: '/(freeRoutes)/home/courseUnavailable/Advanced Sentiment Analysis with Transformers', available: false, time: '0 Hours' },
        { title: 'Text Style Transfer', route: '/(freeRoutes)/home/courseUnavailable/Text Style Transfer', available: false, time: '0 Hours' },
        { title: 'Abstractive Text Summarization with Transformers', route: '/(freeRoutes)/home/courseUnavailable/Abstractive Text Summarization with Transformers', available: false, time: '0 Hours' },
        { title: 'Question Answering with Transformers', route: '/(freeRoutes)/home/courseUnavailable/Question Answering with Transformers', available: false, time: '0 Hours' },
        { title: 'Document Classification with BERT/RoBERTa', route: '/(freeRoutes)/home/courseUnavailable/Document Classification with BERT/RoBERTa', available: false, time: '0 Hours' },
        { title: 'Named Entity Recognition with Transformers', route: '/(freeRoutes)/home/courseUnavailable/Named Entity Recognition with Transformers', available: false, time: '0 Hours' },
        { title: 'Few-Shot Text Classification', route: '/(freeRoutes)/home/courseUnavailable/Few-Shot Text Classification', available: false, time: '0 Hours' },
        { title: 'Text-Based Recommendation Systems', route: '/(freeRoutes)/home/courseUnavailable/Text-Based Recommendation Systems', available: false, time: '0 Hours' },
        { title: 'Conversational AI with LLMs', route: '/(freeRoutes)/home/courseUnavailable/Conversational AI with LLMs', available: false, time: '0 Hours' },
        { title: 'Knowledge Graph Extraction from Text', route: '/(freeRoutes)/home/courseUnavailable/Knowledge Graph Extraction from Text', available: false, time: '0 Hours' },
        { title: 'Multi-Task NLP Models', route: '/(freeRoutes)/home/courseUnavailable/Multi-Task NLP Models', available: false, time: '0 Hours' },
        { title: 'Text-to-Image / Multimodal Generation', route: '/(freeRoutes)/home/courseUnavailable/Text-to-Image / Multimodal Generation', available: false, time: '0 Hours' },
        { title: 'Summarization + Question Answering Pipeline', route: '/(freeRoutes)/home/courseUnavailable/Summarization + Question Answering Pipeline', available: false, time: '0 Hours' },
        { title: 'Fact-Checking / Misinformation Detection', route: '/(freeRoutes)/home/courseUnavailable/Fact-Checking / Misinformation Detection', available: false, time: '0 Hours' },
        { title: 'Automated Essay Scoring / Grading', route: '/(freeRoutes)/home/courseUnavailable/Automated Essay Scoring / Grading', available: false, time: '0 Hours' },
        { title: 'Personalized Conversational Agents', route: '/(freeRoutes)/home/courseUnavailable/Personalized Conversational Agents', available: false, time: '0 Hours' },
        { title: 'Long-Document Understanding', route: '/(freeRoutes)/home/courseUnavailable/Long-Document Understanding', available: false, time: '0 Hours' },
        { title: 'Self-Learning / Auto-Improving Chatbots', route: '/(freeRoutes)/home/courseUnavailable/Self-Learning / Auto-Improving Chatbots', available: false, time: '0 Hours' },
        { title: 'Generative Data Augmentation', route: '/(freeRoutes)/home/courseUnavailable/Generative Data Augmentation', available: false, time: '0 Hours' },
        { title: 'Cross-Lingual NLP Systems', route: '/(freeRoutes)/home/courseUnavailable/Cross-Lingual NLP Systems', available: false, time: '0 Hours' },
        { title: 'Zero-Shot / Few-Shot Reasoning', route: '/(freeRoutes)/home/courseUnavailable/Zero-Shot / Few-Shot Reasoning', available: false, time: '0 Hours' }
    ]
    ,
    'Image': [
        { title: 'Image Classification (Cats vs Dogs)', route: '/(freeRoutes)/home/courseUnavailable/Image Classification (Cats vs Dogs)', available: false, time: '0 Hours' },
        { title: 'Handwritten Digit Recognition (MNIST)', route: '/(freeRoutes)/home/courseUnavailable/Handwritten Digit Recognition (MNIST)', available: false, time: '0 Hours' },
        { title: 'Image Augmentation Pipeline', route: '/(freeRoutes)/home/courseUnavailable/Image Augmentation Pipeline', available: false, time: '0 Hours' },
        { title: 'Basic Image Preprocessing Suite', route: '/(freeRoutes)/home/courseUnavailable/Basic Image Preprocessing Suite', available: false, time: '0 Hours' },
        { title: 'Simple Transfer Learning (MobileNet or ResNet)', route: '/(freeRoutes)/home/courseUnavailable/Simple Transfer Learning (MobileNet or ResNet)', available: false, time: '0 Hours' },
        { title: 'Image Color Classifier', route: '/(freeRoutes)/home/courseUnavailable/Image Color Classifier', available: false, time: '0 Hours' },
        { title: 'Simple Object Detection (Haar Cascade)', route: '/(freeRoutes)/home/courseUnavailable/Simple Object Detection (Haar Cascade)', available: false, time: '0 Hours' },
        { title: 'Image Similarity Finder', route: '/(freeRoutes)/home/courseUnavailable/Image Similarity Finder', available: false, time: '0 Hours' },
        { title: 'Basic Image Segmentation', route: '/(freeRoutes)/home/courseUnavailable/Basic Image Segmentation', available: false, time: '0 Hours' },
        { title: 'Image Compression using PCA', route: '/(freeRoutes)/home/courseUnavailable/Image Compression using PCA', available: false, time: '0 Hours' },
        { title: 'Custom CNN from Scratch', route: '/(freeRoutes)/home/courseUnavailable/Custom CNN from Scratch', available: false, time: '0 Hours' },
        { title: 'Traffic Sign Recognition', route: '/(freeRoutes)/home/courseUnavailable/Traffic Sign Recognition', available: false, time: '0 Hours' },
        { title: 'Facial Expression Recognition', route: '/(freeRoutes)/home/courseUnavailable/Facial Expression Recognition', available: false, time: '0 Hours' },
        { title: 'Plant Disease Detection', route: '/(freeRoutes)/home/courseUnavailable/Plant Disease Detection', available: false, time: '0 Hours' },
        { title: 'Fashion Item Classification', route: '/(freeRoutes)/home/courseUnavailable/Fashion Item Classification', available: false, time: '0 Hours' },
        { title: 'Scene Classification', route: '/(freeRoutes)/home/courseUnavailable/Scene Classification', available: false, time: '0 Hours' },
        { title: 'Food Image Recognition', route: '/(freeRoutes)/home/courseUnavailable/Food Image Recognition', available: false, time: '0 Hours' },
        { title: 'Fine-tuned Transfer Learning with EfficientNet', route: '/(freeRoutes)/home/courseUnavailable/Fine-tuned Transfer Learning with EfficientNet', available: false, time: '0 Hours' },
        { title: 'Image Super-Resolution (SRGAN)', route: '/(freeRoutes)/home/courseUnavailable/Image Super-Resolution (SRGAN)', available: false, time: '0 Hours' },
        { title: 'Image Denoising (Autoencoder)', route: '/(freeRoutes)/home/courseUnavailable/Image Denoising (Autoencoder)', available: false, time: '0 Hours' },
        { title: 'Object Detection with YOLOv8 or SSD', route: '/(freeRoutes)/home/courseUnavailable/Object Detection with YOLOv8 or SSD', available: false, time: '0 Hours' },
        { title: 'Semantic Segmentation with U-Net', route: '/(freeRoutes)/home/courseUnavailable/Semantic Segmentation with U-Net', available: false, time: '0 Hours' },
        { title: 'Instance Segmentation with Mask R-CNN', route: '/(freeRoutes)/home/courseUnavailable/Instance Segmentation with Mask R-CNN', available: false, time: '0 Hours' },
        { title: 'Pose Estimation (OpenPose)', route: '/(freeRoutes)/home/courseUnavailable/Pose Estimation (OpenPose)', available: false, time: '0 Hours' },
        { title: 'Facial Recognition System (FaceNet)', route: '/(freeRoutes)/home/courseUnavailable/Facial Recognition System (FaceNet)', available: false, time: '0 Hours' },
        { title: 'Image Captioning (CNN + LSTM)', route: '/(freeRoutes)/home/courseUnavailable/Image Captioning (CNN + LSTM)', available: false, time: '0 Hours' },
        { title: 'Multi-Label Image Classification', route: '/(freeRoutes)/home/courseUnavailable/Multi-Label Image Classification', available: false, time: '0 Hours' },
        { title: 'Medical Image Classification (X-rays or MRI)', route: '/(freeRoutes)/home/courseUnavailable/Medical Image Classification (X-rays or MRI)', available: false, time: '0 Hours' },
        { title: 'OCR – Optical Character Recognition', route: '/(freeRoutes)/home/courseUnavailable/OCR – Optical Character Recognition', available: false, time: '0 Hours' },
        { title: 'Feature Matching (SIFT/SURF)', route: '/(freeRoutes)/home/courseUnavailable/Feature Matching (SIFT/SURF)', available: false, time: '0 Hours' },
        { title: 'Generative Adversarial Networks (GANs)', route: '/(freeRoutes)/home/courseUnavailable/Generative Adversarial Networks (GANs)', available: false, time: '0 Hours' },
        { title: 'DeepFake Generator (Face Swap)', route: '/(freeRoutes)/home/courseUnavailable/DeepFake Generator (Face Swap)', available: false, time: '0 Hours' },
        { title: 'Style Transfer (Neural Transfer)', route: '/(freeRoutes)/home/courseUnavailable/Style Transfer (Neural Transfer)', available: false, time: '0 Hours' },
        { title: 'Image-to-Image Translation (Pix2Pix / CycleGAN)', route: '/(freeRoutes)/home/courseUnavailable/Image-to-Image Translation (Pix2Pix / CycleGAN)', available: false, time: '0 Hours' },
        { title: 'Diffusion Model (Stable Diffusion Lite)', route: '/(freeRoutes)/home/courseUnavailable/Diffusion Model (Stable Diffusion Lite)', available: false, time: '0 Hours' },
        { title: 'Text-to-Image Generation (CLIP + Diffusion)', route: '/(freeRoutes)/home/courseUnavailable/Text-to-Image Generation (CLIP + Diffusion)', available: false, time: '0 Hours' },
        { title: 'Image Outpainting / Inpainting', route: '/(freeRoutes)/home/courseUnavailable/Image Outpainting / Inpainting', available: false, time: '0 Hours' },
        { title: 'Super Realistic Image Generation (GAN Fine-tuning)', route: '/(freeRoutes)/home/courseUnavailable/Super Realistic Image Generation (GAN Fine-tuning)', available: false, time: '0 Hours' },
        { title: 'AI Art Generator with Prompt Tuning', route: '/(freeRoutes)/home/courseUnavailable/AI Art Generator with Prompt Tuning', available: false, time: '0 Hours' },
        { title: 'Vision Transformer (ViT) from Scratch', route: '/(freeRoutes)/home/courseUnavailable/Vision Transformer (ViT) from Scratch', available: false, time: '0 Hours' },
        { title: 'CLIP Model Implementation', route: '/(freeRoutes)/home/courseUnavailable/CLIP Model Implementation', available: false, time: '0 Hours' },
        { title: 'Visual Question Answering (VQA)', route: '/(freeRoutes)/home/courseUnavailable/Visual Question Answering (VQA)', available: false, time: '0 Hours' },
        { title: 'Image Search Engine (CLIP-based)', route: '/(freeRoutes)/home/courseUnavailable/Image Search Engine (CLIP-based)', available: false, time: '0 Hours' },
        { title: 'Autonomous Vehicle Vision System', route: '/(freeRoutes)/home/courseUnavailable/Autonomous Vehicle Vision System', available: false, time: '0 Hours' },
        { title: 'Satellite Image Analysis', route: '/(freeRoutes)/home/courseUnavailable/Satellite Image Analysis', available: false, time: '0 Hours' },
        { title: '3D Object Reconstruction from Images', route: '/(freeRoutes)/home/courseUnavailable/3D Object Reconstruction from Images', available: false, time: '0 Hours' },
        { title: 'AR Object Detection App', route: '/(freeRoutes)/home/courseUnavailable/AR Object Detection App', available: false, time: '0 Hours' },
        { title: 'AI-Powered Image Editor', route: '/(freeRoutes)/home/courseUnavailable/AI-Powered Image Editor', available: false, time: '0 Hours' },
        { title: 'Medical Image Segmentation for Diagnosis', route: '/(freeRoutes)/home/courseUnavailable/Medical Image Segmentation for Diagnosis', available: false, time: '0 Hours' },
        { title: 'AI Surveillance & Anomaly Detection', route: '/(freeRoutes)/home/courseUnavailable/AI Surveillance & Anomaly Detection', available: false, time: '0 Hours' }
    ]
    ,
    'Video': [
        { title: 'Video Frame Extraction Tool', route: '/(freeRoutes)/home/courseUnavailable/Video Frame Extraction Tool', available: false, time: '0 Hours' },
        { title: 'Basic Video Player with OpenCV', route: '/(freeRoutes)/home/courseUnavailable/Basic Video Player with OpenCV', available: false, time: '0 Hours' },
        { title: 'Motion Detection using Frame Differencing', route: '/(freeRoutes)/home/courseUnavailable/Motion Detection using Frame Differencing', available: false, time: '0 Hours' },
        { title: 'Video Grayscale & Filtering Pipeline', route: '/(freeRoutes)/home/courseUnavailable/Video Grayscale & Filtering Pipeline', available: false, time: '0 Hours' },
        { title: 'Background Subtraction', route: '/(freeRoutes)/home/courseUnavailable/Background Subtraction', available: false, time: '0 Hours' },
        { title: 'FPS & Resolution Analyzer', route: '/(freeRoutes)/home/courseUnavailable/FPS & Resolution Analyzer', available: false, time: '0 Hours' },
        { title: 'Basic Object Detection on Video (YOLO pre-trained)', route: '/(freeRoutes)/home/courseUnavailable/Basic Object Detection on Video (YOLO pre-trained)', available: false, time: '0 Hours' },
        { title: 'Face Detection in Video', route: '/(freeRoutes)/home/courseUnavailable/Face Detection in Video', available: false, time: '0 Hours' },
        { title: 'Video Stabilization (Basic)', route: '/(freeRoutes)/home/courseUnavailable/Video Stabilization (Basic)', available: false, time: '0 Hours' },
        { title: 'Video Compression Analyzer', route: '/(freeRoutes)/home/courseUnavailable/Video Compression Analyzer', available: false, time: '0 Hours' },
        { title: 'Action Recognition (Simple CNN + Frames)', route: '/(freeRoutes)/home/courseUnavailable/Action Recognition (Simple CNN + Frames)', available: false, time: '0 Hours' },
        { title: 'Optical Flow Visualization', route: '/(freeRoutes)/home/courseUnavailable/Optical Flow Visualization', available: false, time: '0 Hours' },
        { title: 'Video Classification (Sports / Activities)', route: '/(freeRoutes)/home/courseUnavailable/Video Classification (Sports / Activities)', available: false, time: '0 Hours' },
        { title: 'Human Activity Recognition', route: '/(freeRoutes)/home/courseUnavailable/Human Activity Recognition', available: false, time: '0 Hours' },
        { title: 'Video Shot Boundary Detection', route: '/(freeRoutes)/home/courseUnavailable/Video Shot Boundary Detection', available: false, time: '0 Hours' },
        { title: 'Video Summarization (Key Frames)', route: '/(freeRoutes)/home/courseUnavailable/Video Summarization (Key Frames)', available: false, time: '0 Hours' },
        { title: 'Face Emotion Detection in Video', route: '/(freeRoutes)/home/courseUnavailable/Face Emotion Detection in Video', available: false, time: '0 Hours' },
        { title: 'Traffic Monitoring System', route: '/(freeRoutes)/home/courseUnavailable/Traffic Monitoring System', available: false, time: '0 Hours' },
        { title: 'Crowd Density Estimation', route: '/(freeRoutes)/home/courseUnavailable/Crowd Density Estimation', available: false, time: '0 Hours' },
        { title: 'Violence / Anomaly Detection (Basic)', route: '/(freeRoutes)/home/courseUnavailable/Violence / Anomaly Detection (Basic)', available: false, time: '0 Hours' },
        { title: '3D CNN for Action Recognition', route: '/(freeRoutes)/home/courseUnavailable/3D CNN for Action Recognition', available: false, time: '0 Hours' },
        { title: 'CNN + LSTM Video Classifier', route: '/(freeRoutes)/home/courseUnavailable/CNN + LSTM Video Classifier', available: false, time: '0 Hours' },
        { title: 'Video Object Tracking (SORT / DeepSORT)', route: '/(freeRoutes)/home/courseUnavailable/Video Object Tracking (SORT / DeepSORT)', available: false, time: '0 Hours' },
        { title: 'Multi-Object Tracking System', route: '/(freeRoutes)/home/courseUnavailable/Multi-Object Tracking System', available: false, time: '0 Hours' },
        { title: 'Person Re-Identification (Video)', route: '/(freeRoutes)/home/courseUnavailable/Person Re-Identification (Video)', available: false, time: '0 Hours' },
        { title: 'Video Captioning (CNN + LSTM)', route: '/(freeRoutes)/home/courseUnavailable/Video Captioning (CNN + LSTM)', available: false, time: '0 Hours' },
        { title: 'Gesture Recognition System', route: '/(freeRoutes)/home/courseUnavailable/Gesture Recognition System', available: false, time: '0 Hours' },
        { title: 'Sports Analytics (Player Tracking)', route: '/(freeRoutes)/home/courseUnavailable/Sports Analytics (Player Tracking)', available: false, time: '0 Hours' },
        { title: 'Face Recognition in Video Streams', route: '/(freeRoutes)/home/courseUnavailable/Face Recognition in Video Streams', available: false, time: '0 Hours' },
        { title: 'Video Quality Enhancement (Denoise / Deblur)', route: '/(freeRoutes)/home/courseUnavailable/Video Quality Enhancement (Denoise / Deblur)', available: false, time: '0 Hours' },
        { title: 'GAN-based Video Generation', route: '/(freeRoutes)/home/courseUnavailable/GAN-based Video Generation', available: false, time: '0 Hours' },
        { title: 'Video Frame Interpolation', route: '/(freeRoutes)/home/courseUnavailable/Video Frame Interpolation', available: false, time: '0 Hours' },
        { title: 'Video Super-Resolution', route: '/(freeRoutes)/home/courseUnavailable/Video Super-Resolution', available: false, time: '0 Hours' },
        { title: 'Video Inpainting', route: '/(freeRoutes)/home/courseUnavailable/Video Inpainting', available: false, time: '0 Hours' },
        { title: 'Video Style Transfer', route: '/(freeRoutes)/home/courseUnavailable/Video Style Transfer', available: false, time: '0 Hours' },
        { title: 'Text-to-Video Generation (Basic)', route: '/(freeRoutes)/home/courseUnavailable/Text-to-Video Generation (Basic)', available: false, time: '0 Hours' },
        { title: 'DeepFake Video Generator', route: '/(freeRoutes)/home/courseUnavailable/DeepFake Video Generator', available: false, time: '0 Hours' },
        { title: 'Talking Head Video Synthesis', route: '/(freeRoutes)/home/courseUnavailable/Talking Head Video Synthesis', available: false, time: '0 Hours' },
        { title: 'Temporal Consistency Optimization', route: '/(freeRoutes)/home/courseUnavailable/Temporal Consistency Optimization', available: false, time: '0 Hours' },
        { title: 'Video Transformer (ViViT / TimeSformer)', route: '/(freeRoutes)/home/courseUnavailable/Video Transformer (ViViT / TimeSformer)', available: false, time: '0 Hours' },
        { title: 'Visual Question Answering on Video', route: '/(freeRoutes)/home/courseUnavailable/Visual Question Answering on Video', available: false, time: '0 Hours' },
        { title: 'Video Search Engine (CLIP-based)', route: '/(freeRoutes)/home/courseUnavailable/Video Search Engine (CLIP-based)', available: false, time: '0 Hours' },
        { title: 'Surveillance AI System', route: '/(freeRoutes)/home/courseUnavailable/Surveillance AI System', available: false, time: '0 Hours' },
        { title: 'Autonomous Driving Video Perception', route: '/(freeRoutes)/home/courseUnavailable/Autonomous Driving Video Perception', available: false, time: '0 Hours' },
        { title: 'Sports Highlight Generator', route: '/(freeRoutes)/home/courseUnavailable/Sports Highlight Generator', available: false, time: '0 Hours' },
        { title: 'Video-Based Recommendation System', route: '/(freeRoutes)/home/courseUnavailable/Video-Based Recommendation System', available: false, time: '0 Hours' },
        { title: 'Live Stream Moderation AI', route: '/(freeRoutes)/home/courseUnavailable/Live Stream Moderation AI', available: false, time: '0 Hours' },
        { title: 'Long-Form Video Understanding (Hours)', route: '/(freeRoutes)/home/courseUnavailable/Long-Form Video Understanding (Hours)', available: false, time: '0 Hours' },
        { title: 'Multimodal Video Agent (Text + Audio + Video)', route: '/(freeRoutes)/home/courseUnavailable/Multimodal Video Agent (Text + Audio + Video)', available: false, time: '0 Hours' },
        { title: 'End-to-End Video AI Platform', route: '/(freeRoutes)/home/courseUnavailable/End-to-End Video AI Platform', available: false, time: '0 Hours' }
    ]
    ,
    'Audio': [
        {
            'title': "Audio Processing",
            'route': '/(freeRoutes)/home/courseUnavailable/Audio Processing',
            'available': false,
            'time': '0 Hours',
        }
    ],
    'Multimodal': [
        { title: 'Text + Image Similarity Search', route: '/(freeRoutes)/home/courseUnavailable/Text + Image Similarity Search', available: false, time: '0 Hours' },
        { title: 'Image Captioning (Pretrained)', route: '/(freeRoutes)/home/courseUnavailable/Image Captioning (Pretrained)', available: false, time: '0 Hours' },
        { title: 'Audio + Text Transcription Viewer', route: '/(freeRoutes)/home/courseUnavailable/Audio + Text Transcription Viewer', available: false, time: '0 Hours' },
        { title: 'Basic Multimodal Dataset Explorer', route: '/(freeRoutes)/home/courseUnavailable/Basic Multimodal Dataset Explorer', available: false, time: '0 Hours' },
        { title: 'Text-Based Image Retrieval', route: '/(freeRoutes)/home/courseUnavailable/Text-Based Image Retrieval', available: false, time: '0 Hours' },
        { title: 'Visual Sentiment Analysis', route: '/(freeRoutes)/home/courseUnavailable/Visual Sentiment Analysis', available: false, time: '0 Hours' },
        { title: 'Multimodal Feature Concatenation', route: '/(freeRoutes)/home/courseUnavailable/Multimodal Feature Concatenation', available: false, time: '0 Hours' },
        { title: 'Product Search (Text + Image)', route: '/(freeRoutes)/home/courseUnavailable/Product Search (Text + Image)', available: false, time: '0 Hours' },
        { title: 'Video + Text Metadata Classifier', route: '/(freeRoutes)/home/courseUnavailable/Video + Text Metadata Classifier', available: false, time: '0 Hours' },
        { title: 'Image Tagging using Text Prompts', route: '/(freeRoutes)/home/courseUnavailable/Image Tagging using Text Prompts', available: false, time: '0 Hours' },
        { title: 'CLIP-style Image–Text Matching', route: '/(freeRoutes)/home/courseUnavailable/CLIP-style Image–Text Matching', available: false, time: '0 Hours' },
        { title: 'Visual Question Answering (Images)', route: '/(freeRoutes)/home/courseUnavailable/Visual Question Answering (Images)', available: false, time: '0 Hours' },
        { title: 'Audio-Visual Emotion Recognition', route: '/(freeRoutes)/home/courseUnavailable/Audio-Visual Emotion Recognition', available: false, time: '0 Hours' },
        { title: 'Multimodal Sentiment Analysis', route: '/(freeRoutes)/home/courseUnavailable/Multimodal Sentiment Analysis', available: false, time: '0 Hours' },
        { title: 'Image + Text Fake News Detection', route: '/(freeRoutes)/home/courseUnavailable/Image + Text Fake News Detection', available: false, time: '0 Hours' },
        { title: 'Video Captioning (Text Output)', route: '/(freeRoutes)/home/courseUnavailable/Video Captioning (Text Output)', available: false, time: '0 Hours' },
        { title: 'Speech-Based Image Search', route: '/(freeRoutes)/home/courseUnavailable/Speech-Based Image Search', available: false, time: '0 Hours' },
        { title: 'Multimodal Recommendation System', route: '/(freeRoutes)/home/courseUnavailable/Multimodal Recommendation System', available: false, time: '0 Hours' },
        { title: 'OCR + NLP Pipeline', route: '/(freeRoutes)/home/courseUnavailable/OCR + NLP Pipeline', available: false, time: '0 Hours' },
        { title: 'Chart / Diagram Understanding', route: '/(freeRoutes)/home/courseUnavailable/Chart / Diagram Understanding', available: false, time: '0 Hours' },
        { title: 'Multimodal Transformer (Text + Image)', route: '/(freeRoutes)/home/courseUnavailable/Multimodal Transformer (Text + Image)', available: false, time: '0 Hours' },
        { title: 'Video + Audio Event Detection', route: '/(freeRoutes)/home/courseUnavailable/Video + Audio Event Detection', available: false, time: '0 Hours' },
        { title: 'Vision-Language Navigation', route: '/(freeRoutes)/home/courseUnavailable/Vision-Language Navigation', available: false, time: '0 Hours' },
        { title: 'Image-Based Reasoning System', route: '/(freeRoutes)/home/courseUnavailable/Image-Based Reasoning System', available: false, time: '0 Hours' },
        { title: 'Multimodal Question Answering (Video)', route: '/(freeRoutes)/home/courseUnavailable/Multimodal Question Answering (Video)', available: false, time: '0 Hours' },
        { title: 'Emotion-Aware Conversational AI', route: '/(freeRoutes)/home/courseUnavailable/Emotion-Aware Conversational AI', available: false, time: '0 Hours' },
        { title: 'Speech-to-Image Generation', route: '/(freeRoutes)/home/courseUnavailable/Speech-to-Image Generation', available: false, time: '0 Hours' },
        { title: 'Visual Dialogue System', route: '/(freeRoutes)/home/courseUnavailable/Visual Dialogue System', available: false, time: '0 Hours' },
        { title: 'Multimodal Fake Content Detection', route: '/(freeRoutes)/home/courseUnavailable/Multimodal Fake Content Detection', available: false, time: '0 Hours' },
        { title: 'Cross-Lingual Multimodal Models', route: '/(freeRoutes)/home/courseUnavailable/Cross-Lingual Multimodal Models', available: false, time: '0 Hours' },
        { title: 'Text-to-Image Generation System', route: '/(freeRoutes)/home/courseUnavailable/Text-to-Image Generation System', available: false, time: '0 Hours' },
        { title: 'Text-to-Video Generation', route: '/(freeRoutes)/home/courseUnavailable/Text-to-Video Generation', available: false, time: '0 Hours' },
        { title: 'Multimodal RAG System', route: '/(freeRoutes)/home/courseUnavailable/Multimodal RAG System', available: false, time: '0 Hours' },
        { title: 'Vision-Language Agent', route: '/(freeRoutes)/home/courseUnavailable/Vision-Language Agent', available: false, time: '0 Hours' },
        { title: 'Document Understanding AI', route: '/(freeRoutes)/home/courseUnavailable/Document Understanding AI', available: false, time: '0 Hours' },
        { title: 'Multimodal ChatGPT-style Assistant', route: '/(freeRoutes)/home/courseUnavailable/Multimodal ChatGPT-style Assistant', available: false, time: '0 Hours' },
        { title: 'Multimodal Memory System', route: '/(freeRoutes)/home/courseUnavailable/Multimodal Memory System', available: false, time: '0 Hours' },
        { title: 'Embodied AI (Vision + Action)', route: '/(freeRoutes)/home/courseUnavailable/Embodied AI (Vision + Action)', available: false, time: '0 Hours' },
        { title: 'Multimodal Prompt Engineering Lab', route: '/(freeRoutes)/home/courseUnavailable/Multimodal Prompt Engineering Lab', available: false, time: '0 Hours' },
        { title: 'Autonomous Multimodal Agent', route: '/(freeRoutes)/home/courseUnavailable/Autonomous Multimodal Agent', available: false, time: '0 Hours' },
        { title: 'Video–Text–Audio Reasoning Engine', route: '/(freeRoutes)/home/courseUnavailable/Video–Text–Audio Reasoning Engine', available: false, time: '0 Hours' },
        { title: 'Scientific Paper Multimodal Analyzer', route: '/(freeRoutes)/home/courseUnavailable/Scientific Paper Multimodal Analyzer', available: false, time: '0 Hours' },
        { title: 'Medical Multimodal Diagnosis AI', route: '/(freeRoutes)/home/courseUnavailable/Medical Multimodal Diagnosis AI', available: false, time: '0 Hours' },
        { title: 'Autonomous Driving Multimodal Brain', route: '/(freeRoutes)/home/courseUnavailable/Autonomous Driving Multimodal Brain', available: false, time: '0 Hours' },
        { title: 'Multimodal Fraud Detection System', route: '/(freeRoutes)/home/courseUnavailable/Multimodal Fraud Detection System', available: false, time: '0 Hours' },
        { title: 'AI Tutor (Vision + Speech + Text)', route: '/(freeRoutes)/home/courseUnavailable/AI Tutor (Vision + Speech + Text)', available: false, time: '0 Hours' },
        { title: 'Multimodal Search Engine (Google-level)', route: '/(freeRoutes)/home/courseUnavailable/Multimodal Search Engine (Google-level)', available: false, time: '0 Hours' },
        { title: 'Long-Horizon Multimodal Planning Agent', route: '/(freeRoutes)/home/courseUnavailable/Long-Horizon Multimodal Planning Agent', available: false, time: '0 Hours' },
        { title: 'Multimodal AI Operating System', route: '/(freeRoutes)/home/courseUnavailable/Multimodal AI Operating System', available: false, time: '0 Hours' },
        { title: 'Research-Grade Multimodal Foundation Model', route: '/(freeRoutes)/home/courseUnavailable/Research-Grade Multimodal Foundation Model', available: false, time: '0 Hours' }
    ]
}

export default coursesList